# Language-specific strings
de:
  title: School of Data Schweiz
  tagline: School of Data Schweiz will den Umgang mit und das Verständnis von Daten fördern.
  description: >
    Wir bieten Unterstützung über <a href="https://forum.schoolofdata.ch">unser Forum</a>
    und organisieren projektbasierte <a href="#info">Workshops</a>:
  current:
    title: Aktuelle Projekte
  signup:
    title: Interessiert?
    header: Ich melde ...
    myself: mich an
    myorg: meine Organisation an
    org: Organisation
    name: Name
    email: E-mail
    comment: Nachricht
    skills: Ich kann ..
    beginner: Formulare ausfüllen
    intermediate: Tabellen verknüpfen
    advanced: Datenbanken abfragen
    expert: Linked Data nutzen
    send: Senden
fr:
  title: L'École de données en Suisse
  tagline: L'École de données promouvoit l'utilisation et la compréhension des données en Suisse.
  description: >
    Nous vous assistons sur <a href="https://forum.schoolofdata.ch">notre forum</a>
    et organisons <a href="#info">des ateliers</a> adaptés aux projets:
  current:
    title: Projets actuels
  signup:
    title: Ça m'interesse!
    header: J'inscris ...
    myself: moi-même
    myorg: mon organisation
    org: Organisation
    name: Nom
    email: E-mail
    comment: Message
    skills: Je peux ..
    beginner: remplir des formulaires
    intermediate: connecter les tables
    advanced: intérroger les Bases de données
    expert: utiliser le Web des données
    send: Envoyer

en:
  title: School of Data Switzerland
  tagline: The School of Data Switzerland supports the usage and understanding of data.
  description: >
    We provide support <a href="https://forum.schoolofdata.ch">on our forum</a>
    and organise project-based <a href="#info">workshops</a>:
  current:
    title: Current projects
  signup:
    title: I'm interested!
    header: Signing up ...
    myself: myself
    myorg: my organisation
    org: Organisation
    name: Name
    email: E-mail
    comment: Message
    skills: I can ..
    beginner: fill out forms
    intermediate: connect spreadsheets
    advanced: run database queries
    expert: use Linked Data sources
    send: Send

# Site links
title: School of Data Switzerland
url: "https://schoolofdata.ch"
email: info@schoolofdata.ch
twitter: schoolofdata
facebook: schoolofdata
github: schoolofdata-swiss
grecaptcha:
  key: 6Lco8A8UAAAAAH68UXg94Ib9ptw6fRGxnZtSb0oQ

# Build settings
baseurl: "" # the subpath, e.g. /blog
markdown: kramdown
sass:
  sass_dir: sass
